-- fornece permissão pública para qualquer operação para as tabelas
-- da aplicação
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON APOSTAS		TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON RANKING 	TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON APOSTADORES TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON RESULTADOS  TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON JOGOS 		TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON SEDES 		TO PUBLIC;	
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON RODADAS 	TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON SELECOES 	TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON ESTADOS 	TO PUBLIC;
GRANT DELETE,INSERT,REFERENCES,SELECT,UPDATE ON GRUPOS 	 	TO PUBLIC;

-- fornece permissão pública para as stored procedures da aplicação
GRANT EXECUTE ON SP_PROCESSAR_PONTUACAO_APOSTADOR TO PUBLIC;
GRANT EXECUTE ON SP_PROCESSAR_PONTUACAO_GERAL	  TO PUBLIC;
GRANT EXECUTE ON SP_PROCESSAR_PONTUACAO_GERAL	  TO PUBLIC;
GRANT EXECUTE ON SP_GERAR_EXTRATO_APOSTAS		  TO PUBLIC;

-- fornece permissão pública para as view's da aplicação
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON V_RANKING TO PUBLIC;